### ISSUE TITLE
Some questions about deblurring

### ISSUE THREAD

**Issue by xuzhiyuan95** [xiaozhi2015/small-code#3]
Hello, I have been doing some  work about deblur recently. Some of the code in DeblurGAN doesn't quite understand. Can you tell me your contact information? I am sorry to delay your time ,I can pay for your help, trouble you

**Comment by xiaozhi2015** [comment]
Sorry for the late reply. In my experience, the grid effect of "DeblurGAN" has not been well solved up to now and the author has released "DeblurGAN-v2" which is "Faster and Better" and more stable. Hope for pure technical communication with qq 2574015660.
